const hiit={work:20,rest:40,rounds:2,selection:'No jumping',run:null};
const intervalSets={'No jumping':['step-jacks','march','side-steps'],'Bodyweight / jumping':['star-jacks','high-knees','squat'],'My session':null};
const hiitButton=(text,action)=>`<button class="full ${action==='start'?'primary':''}" data-hiit="${action}">${text}</button>`;
const beforeHiit=render;
const elapsed=()=>hiit.run.elapsed+(hiit.run.running?(performance.now()-hiit.run.started)/1000:0);
function pauseInterval(){if(hiit.run?.running){hiit.run.elapsed=elapsed();hiit.run.running=false;}}
render=function(){beforeHiit();
 if(['training','builder','today'].includes(state.page))screen.insertAdjacentHTML('afterbegin',hiitButton(hiit.run?'Return to interval timer':'HIIT & interval training','open'));
 if(state.page!=='hiit')return;
 document.querySelector('[data-go="training"]')?.setAttribute('aria-current','page');
 let content=title('HIIT & intervals','Work. Recover.<br>Repeat.');
 if(!hiit.run){content+=`<p>Alternate effort and recovery. HIIT describes intensity, not jumping: a timer alone cannot tell how hard you are working.</p><p class="draft-note">Demo timings, not a personalised prescription. Warm up before starting and allow time to cool down afterwards; neither is included in this timer.</p>${pick('interval-selection','Exercise selection',Object.keys(intervalSets),hiit.selection)}<div class="log-fields"><label>Work seconds<input id="interval-work" type="number" min="5" max="180" value="${hiit.work}"></label><label>Recovery seconds<input id="interval-rest" type="number" min="5" max="180" value="${hiit.rest}"></label><label>Rounds<input id="interval-rounds" type="number" min="1" max="10" value="${hiit.rounds}"></label></div><div class="card"><h3>Exercise order</h3>${(intervalSets[hiit.selection]||training.builder).map(id=>`<p>${ex(id).name}</p>`).join('')||'<p>Add exercises in the session builder first.</p>'}</div><p class="small">The final work interval ends the timer, without an extra recovery interval. Pause or stop whenever needed.</p>${hiitButton('Start demo timer','start')}<p id="interval-error" role="status"></p>`;
 }else{const p=IntervalModel.position(hiit.run.phases,elapsed());content+=`<div class="card feature"><p id="interval-phase" class="eyebrow"></p><h3 id="interval-exercise"></h3><div id="interval-clock" class="metric" role="timer" aria-label="Seconds remaining"></div><p id="interval-round" class="small"></p></div><p id="interval-state" role="status"></p>${hiitButton(hiit.run.running?'Pause timer':'Resume timer','pause')}${hiitButton('End and reset timer','end')}<p class="small">The timer does not mark exercises complete or save a workout automatically. Leaving this screen or hiding the page pauses it. Refreshing clears it.</p>`;}
 screen.innerHTML=content;paintInterval();
};
function paintInterval(){if(state.page!=='hiit'||!hiit.run)return;const p=IntervalModel.position(hiit.run.phases,elapsed());if(p.finished){pauseInterval();document.querySelector('#interval-phase').textContent='Timer finished';document.querySelector('#interval-exercise').textContent='Take time to recover.';document.querySelector('#interval-clock').textContent='0';document.querySelector('#interval-round').textContent='Elapsed intervals do not confirm completed exercise.';document.querySelector('#interval-state').textContent='Finished';const b=document.querySelector('[data-hiit="pause"]');b.disabled=true;b.textContent='Finished';return;}const phase=hiit.run.phases[p.index];document.querySelector('#interval-phase').textContent=phase.kind;document.querySelector('#interval-exercise').textContent=phase.kind==='Work'?ex(phase.id).name:'Recovery interval';document.querySelector('#interval-clock').textContent=p.remaining;document.querySelector('#interval-round').textContent=`Round ${phase.round} of ${hiit.run.rounds} · ${Math.ceil(hiit.run.total)} seconds total`;document.querySelector('#interval-state').textContent=hiit.run.running?'Running':'Paused';}
document.addEventListener('click',e=>{const a=e.target.closest('[data-hiit]')?.dataset.hiit;if(!a)return;if(a==='open')return go('hiit');if(a==='start'){const work=Number(document.querySelector('#interval-work').value),rest=Number(document.querySelector('#interval-rest').value),rounds=Number(document.querySelector('#interval-rounds').value);const ids=intervalSets[hiit.selection]||training.builder;try{const phases=IntervalModel.build(ids,work,rest,rounds);Object.assign(hiit,{work,rest,rounds,run:{phases,rounds,total:phases.reduce((n,p)=>n+p.seconds,0),elapsed:0,started:performance.now(),running:true}});render();}catch(err){document.querySelector('#interval-error').textContent=err.message;}return;}if(a==='pause'){if(hiit.run.running)pauseInterval();else{hiit.run.started=performance.now();hiit.run.running=true;}render();}if(a==='end'){hiit.run=null;render();}});
document.addEventListener('change',e=>{if(e.target.id==='interval-selection'){hiit.work=Number(document.querySelector('#interval-work').value);hiit.rest=Number(document.querySelector('#interval-rest').value);hiit.rounds=Number(document.querySelector('#interval-rounds').value);hiit.selection=e.target.value;render();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){pauseInterval();if(state.page==='hiit')render();}});
setInterval(()=>{if(state.page!=='hiit'){pauseInterval();return;}paintInterval();},200);
document.querySelector('#reset').addEventListener('click',()=>{hiit.run=null;render();});
labels.hiit='HIIT';render();
